version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "23:00"
  - package-ecosystem: "cargo"
    directory: "/crates/fanttheysia-webapp-frontend"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "23:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "23:00"
