[package]
name = "tomestone-dump"
version = "0.1.0"
authors = ["David Cook <divergentdave@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
dotenv = "0.15.0"
hex = "0.4.2"
once_cell = "1.5.2"
regex = "1.4.3"
tomestone-exdf = { path = "../tomestone-exdf" }
tomestone-sqpack = { path = "../tomestone-sqpack" }
tomestone-string-interp = { path = "../tomestone-string-interp" }
