[package]
name = "tomestone-exdf"
version = "0.1.0"
authors = ["David Cook <divergentdave@gmail.com>"]
edition = "2018"

[dependencies]
nom = "6.0.1"
tomestone-common = { path = "../tomestone-common" }
tomestone-sqpack = { path = "../tomestone-sqpack" }

[dev-dependencies]
dotenv = "0.15.0"
