[package]
name = "tomestone-sqpack"
version = "0.1.0"
authors = ["David Cook <divergentdave@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.2.1"
directories = "3.0"
miniz_oxide = "0.4.3"
nom = "6.0.1"
once_cell = "1.5.2"
regex = "1.4.3"
rusqlite = "0.24.2"
sha-1 = "0.9.2"
tomestone-common = { path = "../tomestone-common" }

[dev-dependencies]
dotenv = "0.15.0"
