[package]
name = "tomestone-sqpack"
version = "0.1.0"
authors = ["David Cook <divergentdave@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.1"
sha-1 = "0.9.2"
crc32fast = "1.2.1"
once_cell = "1.5.2"

[dev-dependencies]
dotenv = "0.15.0"
